### ISSUE TITLE
video.py is not included

### ISSUE THREAD

**Issue by ghost** [ashray/Eulerian-Video-Magnification#1]
Import Error at "import video". 
Based on the function from video used, you have not included following file. 
After Including following file I could use the code. 

https://raw.githubusercontent.com/Itseez/opencv/master/samples/python2/video.py

**Comment by ashray** [comment]
Thanks for pointing out the bug, I have solved the problem. For making it even easier to use, I have used ffmpeg now instead of avconv since ffmpeg is more widely used.
